### ISSUE TITLE
Including a large image does not automatically resize to page width

### ISSUE THREAD

**Issue by robogeek** [akashacms/pdf-document-construction-set#44]
Document authors want to easily add images without thinking about it very much.

I had a very wide image, which was not resized to the page width.

Added this style:

```css
article img {
    width: 100%;
}
```

And the image now fits.
