### ISSUE TITLE
From command-line ability to set metadata values

### ISSUE THREAD

**Issue by robogeek** [akashacms/pdf-document-construction-set#74]
Some document creation tasks involve filling in a file with data.  Examples:

* _Thank You NAME_ -- A "thank you" letter to a person, along with details of what they did.  Such as a non-profit acknowledging a donation.
* _Monthly statement_ -- Many services have a monthly "statement" showing transactions through the service.  This is data that goes into a table, along with names and addresses.
* _Sales receipt_ -- For a sales transaction, generate a receipt showing names, addresses, details, amounts, taxes, totals, terms

The general idea is to have a template where data is entered into fields in the template.

In AkashaCMS this would be accomplished with a layout template as the template just mentioned, and another document with metadata. With a layout template `sales-receipt.html.njk`, a sales document, `sales-document.html.njk`, might be:

```
---
layout: sales-receipt.html.njk
data:
    purchaserName: Joe Blow
    purchaseDate: 2025-06-22T10:00:00Z
    items:
        - name: Chewy Stix
          number: 10
          pricePerUnit: 3.99
          taxCode: zyx
    purchaserAddress: 123 Main Street
---
```

The template knows to look for fields of the `data` object and use this to fill in the template.

With PDF Document Maker, one could generate a file like the above, inject it into a `documents` directory, then use `pdf-document-maker render` to generate the file.

Or... if this command supported injecting just the metadata...?  I'm not sure at this point what I'm thinking.

The goal is to support scripting an interaction where PDF Document Maker receives a metadata object that is then used in a document.

So... `sales-document.html.njk` would simply be:

```
---
layout: sales-receipt.html.njk
---
```

And an external metadata object is merged with this frontmatter before rendering.  But, what's the point.

Perhaps a metadata/frontmatter document is provided without making it a file in the `documents` directory.  But what's the point?

Perhaps there is nothing to do.. other than to write a HOWTO document on the above scenario.
